---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: adoptopenjdk/openjdk11
      
inputs:
- name: api-tkaburagi

caches:
- path: api-tkaburagi/m2

run:
  path: api-tkaburagi/ci/tasks/integration.sh
  args: [
    --input-dir, api-tkaburagi
  ]
