---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: api-tkaburagi
- name: candidate-release
- name: version

outputs:
- name: prepare-final

run:
  path: api-tkaburagi/ci/tasks/prepare-final.sh
  args: [
    --input-dir, candidate-release,
    --output-dir, prepare-final,
    --version-file, version/number,
    --artifactId, demo,
    --packaging, jar
  ]
